on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/
        key: ${{ hashFiles('build.gradle') }}
    - name: prepare
      run: ./gradlew --build-cache prep
    - name: test
      run: ./gradlew test

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: jacoco
